apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-persistent
  template:
    metadata:
      labels:
        app: nginx-persistent
    spec:
      containers:
      - name: nginx
        image: quay.io/sclorg/nginx-122-micro-c9s # A simple Nginx image
        ports:
        - containerPort: 8080
        command: ["nginx"]
        args: ["-g", "daemon off;"]
        volumeMounts:
        - name: web-content-storage # Name of the volume mount
          mountPath: "/opt/app-root/src" # Path inside the container where content will be stored
      volumes:
      - name: web-content-storage # Matches the volumeMounts name
        persistentVolumeClaim:
          claimName: web-content-pvc # References our PVC