apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx-sts-service
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None # This makes it a "headless" service
  selector:
    app: nginx-sts # Selects pods from our StatefulSet