apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-anti-affinity
spec:
  replicas: 2 # Deploy 2 instances to demonstrate separation
  selector:
    matchLabels:
      app: nginx-anti-affinity
  template:
    metadata:
      labels:
        app: nginx-anti-affinity # This label identifies the pods for anti-affinity
    spec:
      containers:
      - name: nginx
        image: quay.io/sclorg/nginx-122-micro-c9s
        ports:
        - containerPort: 8080
        command: ["nginx"]
        args: ["-g", "daemon off;"]
      affinity: # <--- New section for affinity
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # Required
            - labelSelector:
                matchLabels:
                  app: nginx-anti-affinity # Target pods with this label (i.e., other pods from this same deployment)
              topologyKey: kubernetes.io/hostname # Ensure separation across different nodes